language: go

go:
  - 1.4
  - tip

before_script:
  - psql -c 'create database gossha_test;' -U postgres
  - mysql -e 'create database gossha_test;'


script: go test

services:
  - postgresql
  - mysql
